package pro.carl.edu.sagan1.logic;

/**
 * Contains application version and title, generated by ANT based on 
 * template Versions-java-template. 
 *
 * @since 0.0
 * @version 1.0.0 - 20/10/2011
 */
abstract public class Versions {

    final public static String APP_TITLE="Sagan One - Robot Simulator";
     
    final public static String APP_VERSION="1.0.0 beta [15/03/2012]";
}
